---
title: "Predição de Votação de Deputados"
author: "Luiz Fernando da Silva"
date: "26 de novembro de 2018"
output: html_document
---


```{r}
library(tidyverse)
library(caret)
```

```{r}
data_train <- read.csv("data/train.csv")
data_train <- data_train %>% select(-nome, -uf,
                 -estado_civil, -partido,
                 -ocupacao,-ano,
                 -cargo,-grau,-sexo,
                 -sequencial_candidato)

data_test <- read_csv("data/test.csv")
```


```{r}
data_train %>% 
  group_by(situacao) %>%
  summarise(n_eleitos=(n()/nrow(data_train))*100) %>%
  ggplot(aes(x=situacao, y=n_eleitos, fill=situacao)) + geom_col() + labs(x = "Situação", y = "Percentual")
```

```{r}
k <- expand.grid(k = seq(20,100, length=81))
fitControl <- trainControl(method = "cv", number = 10, repeats = 5)  

model_knn <- train(situacao ~ ., 
                     data = data_train, 
                     method = "knn", 
                     tuneGrid = k,
                     preProc = c("center", "scale"),
                     trControl = fitControl)
plot(model_knn)
model_knn
```

```{r}
model_logistc <- train(situacao ~ ., 
                     data = data_train, 
                     method = "glm", 
                     family = "binomial",
                     preProc = c("center", "scale"),
                     trControl = fitControl)
model_logistc
```

```{r}
trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
set.seed(3333)
dtree_fit <- train(situacao ~., data = data_train, method = "rpart",
                   trControl = trctrl,
                   tuneLength = 10)
dtree_fit
```

```{r}
model_ada <- train(situacao ~ ., 
                     data = data_train, 
                     method = "ada", 
                     preProc = c("center", "scale"),
                     trControl = fitControl)
model_ada
```


```{r}
prediction <- predict(model_logistc, data_test)

data_out <- data.frame(ID = data_test$sequencial_candidato, Predicted = prediction)
data_out$ID <-as.character(data_out$ID) 
data_out %>% write_csv(path = "data/out2.csv")
```

