---
title: 'Análise de Gastos de Deputados: Nossas Perguntas'
author: "Luiz Fernando da Silva"
date: "27 de agosto de 2018"
output: html_document
---

```{r}
library('tidyverse')
library('gridExtra')
options(scipen = 999)
```
```{r}
data <- read_csv('data/dadosCEAP.csv')
limites <- read_csv('data/limiteMensalCEAP.csv')
data %>% full_join(limites, by=c("sgUF" = "UF")) -> data
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Questão 1
```{r}
maisGastadores <- data %>%
  filter(valorLíquido > 0) %>%
  group_by(nomeParlamentar) %>% 
  summarise(total = sum(valorLíquido)) %>% 
  arrange(-total) %>% 
  slice(1:5)

menosGastadores <- data %>%
  filter(valorLíquido > 0) %>%
  group_by(nomeParlamentar) %>% 
  summarise(total = sum(valorLíquido)) %>% 
  arrange(total) %>% 
  slice(1:5)

gastos <- union(maisGastadores, menosGastadores)

gastos %>% 
  ggplot(aes(x=reorder(nomeParlamentar, total), y=total, fill=nomeParlamentar)) + geom_col(width = 0.7) + coord_flip() +
  guides(fill=guide_legend("Nome do Parlamentar"))
```

# Questão 2
```{r}
maiorGastoExterior <- data %>% 
  group_by(sgUF) %>%
  filter(tipoDocumento == 2) %>% 
  summarise(total = sum(valorLíquido)) %>%
  arrange(-total) %>%
  slice(1:5)

menorGastoExterior <- data %>% 
  group_by(sgUF) %>%
  filter(tipoDocumento == 2) %>% 
  summarise(total = sum(valorLíquido)) %>%
  arrange(total) %>%
  slice(1:5)

gastosExterior <- union(maiorGastoExterior, menorGastoExterior)

gastosExterior %>% 
  ggplot(aes(x=reorder(sgUF, total), y=total, fill=sgUF)) + geom_col(width = 0.7) + coord_flip() + guides(fill=guide_legend("Estado"))
```

# Questão 3

```{r}
gastosPartidosPB <- data %>% 
  filter(sgUF == "PB") %>%
  group_by(sgPartido) %>%
  summarise(total = sum(valorLíquido)) %>%
  arrange(total)


gastosPartidosPB %>% ggplot(aes(x=reorder(sgPartido, total), y=total, fill=sgPartido)) + geom_col(width = 0.7) + coord_flip() + labs(x="Partido", y="Gasto total") + guides(fill=guide_legend("Partido"))
```

# Questão 4
```{r}
dados <- data %>% group_by(nomeParlamentar, limite_mensal) %>%
  summarise(total = sum(valorLíquido)) %>%
  filter(limite_mensal < total) %>%
  ungroup() %>%
  arrange(-total) %>%
  slice(1:10)

dados %>% ggplot(aes(x=reorder(nomeParlamentar, total), y=total, fill=nomeParlamentar)) + geom_col(width = 0.7, show.legend = FALSE) + coord_flip()
```


# Questão 5
```{r}
maiorGastos <- data %>%
  filter(tipoDespesa == "PASSAGENS AÉREAS") %>%
  group_by(sgUF) %>%
  summarise(total = sum(valorLíquido)) %>% na.omit()

maiorGastos %>% ggplot(aes(x=reorder(sgUF, total), y=total, fill=sgUF)) + geom_col(width = 0.7, show.legend = FALSE) + coord_flip() + labs(x="Estado", y="Gasto total")
```

# Questão 6
```{r}
partidos <- data %>% filter(sgPartido %in% c("PT", "PMDB", "PSDB"))

gastos <- partidos %>% group_by(tipoDespesa) %>%
  summarise(total = sum(valorLíquido)) %>%
  arrange(-total)

gastos %>% ggplot(aes(x=reorder(tipoDespesa, total), y=total, fill=tipoDespesa)) + geom_col(width = 0.7, show.legend = FALSE) + coord_flip() + labs(x="Tipo de Despesa", y="Gasto total")
```

